#Google Analytics
analytics-id: #leave blank to not use Analytics

#Subtitle
subtitle:
  active: true
  text: |
    <h2>Read me waffle about my hobbies, food, or anything goes.<h2>
    <h2>Work related goes on <a href="https://bennpham.gitlab.io/">https://bennpham.gitlab.io/</a>.</h2>

#Nav
nav:
  pages:
    active: true
  social:
    active: true

#Featured images in homepage
featured-img:
  active: true

#Show categories at the end of posts
categories:
  active: true

#Show date and read time under the post title
date-under-post:
  active: true

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: true
  title: "You May Also Enjoy"

#Comments
comments: true